### ISSUE TITLE
unbalanced transport

### ISSUE THREAD

**Issue by zsteve** [rsinghlab/SCOT#1]
Hi there,

First thanks for a great method and paper. I've recently been looking at integrating scATAC-seq and scRNA-seq datasets for identically prepared but distinct cell populations. In doing so, one issue that I am wary of is that cell populations may not be represented in identical proportions in both datasets due to sampling or batch-to-batch variation in abundance. As a result, using balanced transport can result in erroneous assignment of mass between domains.

To address this, I've experimented with using an unbalanced Gromov-Wasserstein formulation and demonstrated some examples of this in two notebooks (one simulated dataset and also in SNARE-seq example). I have implemented this in a fork of the repo here: https://github.com/zsteve/SCOT

Although these modifications were motivated by my own use case, I thought this extension might be useful more generally as part of the package. If you are interested, let me know and I can make a pull request.

Stephen

**Comment by pinardemetci** [comment]
Hi Stephen,

Firstly, thanks a lot for opening this useful issue, as well as the experiments in your forked repository. The explanations in your notebooks look great and are even complete with proper references and the results look very nice, too!

Your issue brings up a good point: it is not too uncommon to have some cell types underrepresented in one of the domains (or sometimes even completely missing cell types in a domain, although it is a less common scenario).
We started experimenting with this scenario a little too close to a submission deadline. One thing that we were not yet able to assess was whether GW distance could _still_ be used as a reliable approximation for alignment quality in fully unsupervised settings in this scenario. This would be important when there is no correspondence information available to carry our hyperparameter tuning.  SCOT with balanced OT is able to use this approximation for self-tuning its hyperparameters in fully unsupervised settings (the unsupervised_scot() function in src/scot.py -- I believe our bioRxiv preprint has been updated with those results recently but we will also need to update the repo with notebook demonstrations soon). 

It sounds to me that your case of aligning data from identically prepared but distinct cell populations would require _fully_ unsupervised alignment, as well, right? Have you been able to obtain trustworthy alignments with any of the available methods or with your unbalanced OT implementation?

Going back to your forked repository, I will go ahead and create a pull request and make sure to explicitly acknowledge your contributions in our repo (and the GitHub pages we are creating for the repo and whatever material would be relevant moving forward). We'll also continue to experiment with the fully unsupervised alignment in this setting. In the meantime, I think your contributions will be valuable to have available to people, who have similar application scenarios. Even without the fully unsupervised tuning, it could be used with recommended hyperparameter ranges (epsilon= 5e-4 to 1e-3 range, which seems to affect the result more than the k hyperparameter). Again, thank you for opening this issue and for your experiments. We are always excited to have interactions that stem from common research interest!  Also, let us know if we can do anything to help out with the alignment of your datasets.
