### ISSUE TITLE
Mismatch between number of cells and number of labels for Splatter simulations

### ISSUE THREAD

**Issue by DylanMannKrzisnik** [rsinghlab/SCOT#16]
It seems there are only 4000 labels in `splatter_labels.csv` for 5000 cells in `splatter_X.npy` and `splatter_Y.npy`. I realize that I could recreate the simulations (splatter + random projections), but was hoping I could reuse your simulations. Thanks.

**Comment by pinardemetci** [comment]
Hi Dylan,

I re-uploaded the `splatter_labels.csv` file and double-checked that it has 5000 entries. Each row in the `splatter_labels.csv` correspond to the cell type of the cell on the same row of `splatter_X.npy` or `splatter_y.npy`. Just to roughly double-check they are correct, I reduce `splatter_X.npy`, and `splatter_y.npy` files to 2D via PCA and plot them with these labels, I get the following figures, which appear to be what we expect based on the figures in the publication. Let me know if you run into any issues.
<img width="250" alt="splatter_y" src="https://github.com/rsinghlab/SCOT/assets/7781509/7a3b9a36-9643-4a80-99ee-1342eb62beeb">
<img width="250" alt="splatter_X" src="https://github.com/rsinghlab/SCOT/assets/7781509/e7177148-2967-4f44-8243-e688411420be">

**Comment by pinardemetci** [comment]
closing this for now, if this doesn't fix the issue, feel free to re-open it or comment.
