### ISSUE TITLE
installing the dependencies using requirements.txt

### ISSUE THREAD

**Issue by jiayueg** [rsinghlab/SCOT#5]
Hi, I wonder if there is requirements.txt in this repo, or we should create it by ourselves

**Comment by Cbaker37** [comment]
Hi,

I've attached the requirements.txt file below, in case anyone has a similar question. If you reclone with all of the new code now, it should be included. Thanks!


[requirements.txt](https://github.com/rsinghlab/SCOT/files/12185478/requirements.txt)
